### ISSUE TITLE
Not working with python3.8

### ISSUE THREAD

**Issue by MustafaAnasKH99** [walwe/md2pdf#3]
Error:

```
Traceback (most recent call last):
  File "/usr/bin/md2pdf", line 5, in <module>
    from markdown2pdf import main
  File "/usr/lib/python3.8/site-packages/markdown2pdf/__init__.py", line 20
    print css_file
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(css_file)?
```

**Comment by walwe** [comment]
This python package and repository is called md2pdf and not [markdown2pdf](https://github.com/kxxoling/markdown2pdf).
I very much hope to never put any print into `__init__.py`

**Comment by MustafaAnasKH99** [comment]
Oops .. :D 
sorry for the misunderstanding @walwe !
